export const ACTIVIDADES = [
    {value: '', label:''},
    {value: 'Análisis - Soporte suministrador para análisis', label:'Análisis - Soporte suministrador para análisis'},
    {value: 'Certificación - Certificación proyecto', label:'Certificación - Certificación proyecto'},
    {value: 'Certificación - Soporte a la certificación', label:'Certificación - Soporte a la certificación'},
    {value: 'Consulta - Soporte OM', label:'Consulta - Soporte OM'},
    {value: 'Desarrollo - Construcción de software', label:'Desarrollo - Construcción de software'},
    {value: 'Desarrollo - Entrega DT', label:'Desarrollo - Entrega DT'},
    {value: 'Desarrollo - Soporte del suministrador', label:'Desarrollo - Soporte del suministrador'},
    {value: 'Faculty (MX561002)', label:'Faculty (MX561002)'},
    {value: 'Family Medical Leave (916X00)', label:'Family Medical Leave (916X00)'},
    {value: 'Horas Extras tomadas', label:'Horas Extras tomadas'},
    {value: 'Illness - enfermedad)(950X00)', label:'Illness - enfermedad)(950X00)'},
    {value: 'Implementación - Soporte a la implementación', label:'Implementación - Soporte a la implementación'},
    {value: 'Incidencia', label:'Incidencia'},
    {value: 'Incidencia mal asignada', label:'Incidencia mal asignada'},
    {value: 'Incidencia en Guardia', label:'Incidencia en Guardia'},
    {value: 'Licencia por examen (957X00)', label:'Licencia por examen (957X00)'},
    {value: 'Licencia por maternidad (917X00)', label:'Licencia por maternidad (917X00)'},
    {value: 'Licencia por paternidad (957X02)', label:'Licencia por paternidad (957X02)'},
    {value: 'Licencia sin goce de sueldo (957X04)', label:'Licencia sin goce de sueldo (957X04)'},
    {value: 'National Holiday - Feriados (970X00)', label:'National Holiday - Feriados (970X00)'},
    {value: 'New Hire (Induccion) (935X00)', label:'New Hire (Induccion) (935X00)'},
    {value: 'Otras Ausencias Autorizadas (957X06)', label:'Otras Ausencias Autorizadas (957X06)'},
    {value: 'Otras Licencias Autorizadas (955X00)', label:'Otras Licencias Autorizadas (955X00)'},
    {value: 'Performance Achievement', label:'Performance Achievement'},
    {value: 'Post - implementación - Soporte Post-implementación', label:'Post - implementación - Soporte Post-implementación'},
    {value: 'SQA', label:'SQA'},
    {value: 'Training (MX561025)', label:'Training (MX561025)'},
    {value: 'Vacation (900X00)', label:'Vacation (900X00)'}


]