export const APPS = [
    {value: '', label:''},
    {value: 'ADC', label: 'ADC'}, 
    {value: 'Aplicacion 110', label: 'Aplicacion 110'},
    {value: 'ATIS CO', label: 'ATIS CO'},
    {value: 'ATIS FA', label: 'ATIS FA'},
    {value: 'ATIS IN', label: 'ATIS IN'},
    {value: 'ATIS Proceso Intermedio', label: 'ATIS Proceso Intermedio'},
    {value: 'BANELCO', label: 'BANELCO'},
    {value: 'CARRIER FCO', label: 'CARRIER FCO'},
    {value: 'CARRIER FYC', label: 'CARRIER FYC'},
    {value: 'CARRIER ITX', label: 'CARRIER ITX'},
    {value: 'CC3 Tarificador', label: 'CC3 Tarificador'},
    {value: 'CEAP', label: 'CEAP'},
    {value: 'CIRCUITOS LINK', label: 'CIRCUITOS LINK'},
    {value: 'COATIS', label: 'COATIS'},
    {value: 'Collections Interac', label: 'Collections Interac'},
    {value: 'Consumos Propios', label: 'Consumos Propios'},
    {value: 'COVA Batch', label: 'COVA Batch'},
    {value: 'CPP-Liq', label: 'CPP-Liq'},
    {value: 'CPP-OLD', label: 'CPP-OLD'},
    {value: 'DDA', label: 'DDA'},
    {value: 'DOC1 AMDOCS', label: 'DOC1 AMDOCS'},
    {value: 'DOC1 ATIS', label: 'DOC1 ATIS'},
    {value: 'DOC1 EXMOVICOM', label: 'DOC1 EXMOVICOM'},
    {value: 'DOC1 SIGECO', label: 'DOC1 SIGECO'},
    {value: 'DOCUMENTOS HUERFANOS', label: 'DOCUMENTOS HUERFANOS'}, 
    {value: 'ePagos', label: 'ePagos'},
    {value: 'Facturacion detallada', label: 'Facturacion detallada'},
    {value: 'Facturacion personalizada', label: 'Facturacion personalizada'},
    {value: 'FACTURADOR PC', label: 'FACTURADOR PC'}, 
    {value: 'FacturaElectronicaE/Facturador Plus', label: 'FacturaElectronicaE/Facturador Plus'},
    {value: 'FC&O', label: 'FC&O'},
    {value: 'GIT Tasador', label: 'GIT Tasador'},
    {value: 'ITX Interconexión Movil', label: 'ITX Interconexión Movil'},
    {value: 'MACVAL', label: 'MACVAL'},
    {value: 'Mauliv Web', label: 'Mauliv Web'},
    {value: 'MDR Mediador', label: 'MDR Mediador'}, 
    {value: 'MEMCO', label: 'MEMCO'},
    {value: 'Mercado Pago', label: 'Mercado Pago'},
    {value: 'MOL ATM', label: 'MOL ATM'},
    {value: 'MoviCOP', label: 'MoviCOP'},
    {value: 'MoviDAC', label: 'MoviDAC'},
    {value: 'On Line de Consumos', label: 'On Line de Consumos'},
    {value: 'PANEL DE CONTROL', label: 'PANEL DE CONTROL'},
    {value: 'POL', label: 'POL'},
    {value: 'Portal PRM', label: 'Portal PRM'},
    {value: 'PSF', label: 'PSF'},
    {value: 'RECLATIS', label: 'RECLATIS'},
    {value: 'Reco Online', label: 'Reco Online'},
    {value: 'RECOLECTOR DE PAGOS', label: 'RECOLECTOR DE PAGOS'},
    {value: 'Rentas-Padron', label: 'Rentas-Padron'},
    {value: 'Repartidor Sigres', label: 'Repartidor Sigres'},
    {value: 'Riesgo Crediticio', label: 'Riesgo Crediticio'},
    {value: 'RNP', label: 'RNP'},
    {value: 'Roaming Internacional', label: 'Roaming Internacional'},
    {value: 'Roaming Nacional', label: 'Roaming Nacional'},
    {value: 'RUC', label: 'RUC'},
    {value: 'RVA', label: 'RVA'},
    {value: 'SAT/TIOR', label: 'SAT/TIOR'}, 
    {value: 'SGU Distribucion', label: 'SGU Distribucion'}, 
    {value: 'SGU Facturación', label: 'SGU Facturación'}, 
    {value: 'SIGECO Clientes', label: 'SIGECO Clientes'},
    {value: 'SIGECO Cobros', label: 'SIGECO Cobros'},
    {value: 'SIGECO Facturacion', label: 'SIGECO Facturacion'},
    {value: 'Simaf', label: 'Simaf'},
    {value: 'Sipeyco', label: 'Sipeyco'},
    {value: 'SIPEYCO Batch', label: 'SIPEYCO Batch'},
    {value: 'Temis', label: 'Temis'},
    {value: 'Web Facturacion Datos/Anexos AFIP', label: 'Web Facturacion Datos/Anexos AFIP'},
    {value: 'Web Impago/Aviso de Pagos', label: 'Web Impago/Aviso de Pagos'},
    {value: 'Web Legacy', label: 'Web Legacy'},
    {value: 'WS Reco Impagos', label: 'WS Reco Impagos'},
    {value: 'WSWebs', label: 'WSWebs'}

    /*
	{value: ADC, label: 'ADC'}, 
    "value: App110, label: 'Aplicacion 110'",
    "value: ATISCO, label: 'ATIS CO'",
    "value: ATISFA, label: 'ATIS FA'",
    "value: ATISIN, label: 'ATIS IN'",
    "value: ATISPrIn, label: 'ATIS Proceso Intermedio'",
    "value: BANELCO, label: 'BANELCO'",
    "value: CARRIERFCO, label: 'CARRIER FCO'",
    "value: CARRIERFYC, label: 'CARRIER FYC'",
    "value: CARRIERITX, label: 'CARRIER ITX'",
    "value: CC3Tar, label: 'CC3 Tarificador'",
    "value: CEAP, label: 'CEAP'",
    "value: CIRCUITOSLINK, label: 'CIRCUITOS LINK'",
    "value: COATIS, label: 'COATIS'",
    "value: Collections, label: 'Collections Interac'",
    "value: ConProp, label: 'Consumos Propios'",
    "value: COVABatch, label: 'COVA Batch'",
    "value: CPPLiq, label: 'CPP-Liq'",
    "value: CPPOLD, label: 'CPP-OLD'",
    "value: DDA, label: 'DDA'",
    "value: DOC1AMDOCS, label: 'DOC1 AMDOCS'",
    "value: DOC1ATIS, label: 'DOC1 ATIS'",
    "value: DOC1EXMOV, label: 'DOC1 EXMOVICOM'",
    "value: DOC1SIG, label: 'DOC1 SIGECO'",
    "value: DOCHUERFANOS, label: 'DOCUMENTOS HUERFANOS'", 
    "value: ePagos, label: 'ePagos'",
    "value: Factdetallada, label: 'Facturacion detallada'",
    "value: Factperso, label: 'Facturacion personalizada'",
    "value: FACTURADORPC, label: 'FACTURADOR PC'", 
    "value: FactElecEFactPlus, label: 'FacturaElectronicaE/Facturador Plus'",
    "value: FCO, label: 'FC&O'",
    "value: GIT, label: 'GIT Tasador'",
    "value: ITXInterMov, label: 'ITX Interconexión Movil'",
    "value: MACVAL, label: 'MACVAL'",
    "value: Mauliv, label: 'Mauliv Web'",
    "value: MDR, label: 'MDR Mediador'", 
    "value: MEMCO, label: 'MEMCO'",
    "value: MerPago, label: 'Mercado Pago'",
    "value: MOL, label: 'MOL ATM'",
    "value: MoviCOP, label: 'MoviCOP'",
    "value: MoviDAC, label: 'MoviDAC'",
    "value: OnLineCon, label: 'On Line de Consumos'",
    "value: PACO, label: 'PANEL DE CONTROL'",
    "value: POL, label: 'POL'",
    "value: PSF, label: 'PSF'",
    "value: RECLATIS, label: 'RECLATIS'",
    "value: RecoOn, label: 'Reco Online'",
    "value: RECPAGOS, label: 'RECOLECTOR DE PAGOS'",
    "value: RenPadron, label: 'Rentas-Padron'",
    "value: Repartidor, label: 'Repartidor Sigres'",
    "value: RiesgoCred, label: 'Riesgo Crediticio'",
    "value: RNP, label: 'RNP'",
    "value: RoaInt, label: 'Roaming Internacional'",
    "value: RoaNac, label: 'Roaming Nacional'",
    "value: RUC, label: 'RUC'",
    "value: RVA, label: 'RVA'",
    "value: SATTIOR, label: 'SAT/TIOR'", 
    "value: SGUDis, label: 'SGU Distribucion'", 
    "value: SGUFact, label: 'SGU Facturación'", 
    "value: SIGECOCli, label: 'SIGECO Clientes'",
    "value: SIGECOCob, label: 'SIGECO Cobros'",
    "value: SIGECOFact, label: 'SIGECO Facturacion'",
    "value: Simaf, label: 'Simaf'",
    "value: Sipeyco, label: 'Sipeyco'",
    "value: SIPEYCOBatch, label: 'SIPEYCO Batch'",
    "value: Temis, label: 'Temis'",
    "value: FactDatAnAFIP, label: 'Web Facturacion Datos/Anexos AFIP'",
    "value: ImpagoAvPagos, label: 'Web Impago/Aviso de Pagos'",
    "value: WebLegacy, label: 'Web Legacy'",
    "value: WSRecoImpagos, label: 'WS Reco Impagos'",
    "value: WSWebs, label: 'WSWebs'"
*/
]